In [1]:
# import necessary libraries
import os
import numpy as np
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from skimage import io
from skimage.transform import resize
from sklearn.model_selection import train_test_split

In [2]:
# define the path to the dataset
dataset_path = 'C:/Users/LOKESH/OneDrive/Desktop/Dataset'

# load the dataset
X = []  # list to store feature vectors
y = []  # list to store labels


In [3]:

# loop through the dataset and extract features and labels
for subdir, dirs, files in os.walk(dataset_path):
    for file in files:
        # load the image and resize it
        image_path = os.path.join(subdir, file)
        image = io.imread(image_path)
        resized_image = resize(image, (64, 64), anti_aliasing=True)
        # extract features from the resized image and add it to the X list
        features = np.array(resized_image).flatten()
        X.append(features)
        # extract the label from the filename and add it to the y list
        label = subdir.split(os.path.sep)[-1]
        y.append(label)


In [4]:

# convert X and y to numpy arrays
X = np.array(X)
y = np.array(y)

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# train an SVM model with OvR method
svm_model = svm.SVC(kernel='linear', C=1, gamma='auto', decision_function_shape='ovr')
svm_model.fit(X_train, y_train)


SVC(C=1, gamma='auto', kernel='linear')

In [5]:
train_dataset = (X_train,X_train)

In [6]:
# use the trained model to make predictions on the testing set
y_pred = svm_model.predict(X_test)

In [7]:
# calculate and print the confusion matrix and classification report
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[52  4  3  0  0  0  0  0  0  2]
 [ 9  8  6  2  2  0  1  4  1  0]
 [ 2  6 28  3  0  0  2  1  1  2]
 [ 2  1  5 33  5  1  0  0  0  3]
 [ 1  1  6  6 35  2  0  3  2  3]
 [ 0  2  1  0  3 50  1  0  0  0]
 [ 1  0  1  0  0  0 37  0  0  0]
 [ 2  2  2  1  8  1  0 30  2  2]
 [ 4  2  2  0  4  4  0  1 27  1]
 [ 8  1  4  0  1  0  0  2  0 56]]
Classification Report:
                    precision    recall  f1-score   support

   Bacterial_Spot       0.64      0.85      0.73        61
     Early_Blight       0.30      0.24      0.27        33
            Late_       0.48      0.62      0.54        45
        Leaf_Mold       0.73      0.66      0.69        50
        Leaf_Spot       0.60      0.59      0.60        59
           Mosaic       0.86      0.88      0.87        57
  Powdery_Mildway       0.90      0.95      0.92        39
      Spider_Mite       0.73      0.60      0.66        50
      Target_Spot       0.82      0.60      0.69        45
Yellow_Leaf_Curl_       0.81      0

In [8]:
# import necessary libraries
import numpy as np
from sklearn import svm
from skimage import io
from skimage.transform import resize

In [9]:
# load the testing image
testing_image = io.imread("E:/Healthy/000bf685-b305-408b-91f4-37030f8e62db___GH_HL Leaf 308.1_flipTB.jpg")
resized_image = resize(testing_image, (64, 64), anti_aliasing=True)
image_data = np.array(resized_image).reshape(1, -1)

In [10]:
# use the trained SVM model to predict the class of the testing image
predicted_class = svm_model.predict(image_data)

# print the predicted class
if predicted_class == 0:
    print("The testing image does not have tomato disease.")
else:
    print("The testing image has tomato disease.")


The testing image has tomato disease.


C:\Users\LOKESH\AppData\Local\Temp\ipykernel_14528\3317228187.py:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if predicted_class == 0:
